services:
  postgres:
    container_name: tron_postgres
    image: postgres:16.8
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tron_db
    volumes:
      - tron_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tron_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    container_name: tron_service
    build:
      context: ./source/
    depends_on:
      - postgres
    ports:
      - "8000:8000"

volumes:
 tron_data: