"""init

Revision ID: 368d77d8b663
Revises:
Create Date: 2025-04-19 19:00:19.935997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368d77d8b663'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_queries',
                    sa.Column('address', sa.String(), nullable=True),
                    sa.Column('bandwidth', sa.Integer(), nullable=True),
                    sa.Column('energy', sa.Integer(), nullable=True),
                    sa.Column('balance', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_wallet_queries_address'), 'wallet_queries', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_queries_address'), table_name='wallet_queries')
    op.drop_table('wallet_queries')
    # ### end Alembic commands ###
